# Production base configuration (kept primary)
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production

  # Production server setup
  server:
    host: 0.0.0.0
    port: 8080
    ssl_enabled: true

  # Production logging setup
  logging:
    level: INFO
    format: json
    output: /var/log/app.log

  # Production database (kept intact)
  database:
    host: prod-db.example.com
    port: 5432
    name: devops_prod

  # Core production features
  features:
    auto_scaling: true
    load_balancer: enabled
    backup_enabled: true

  # Optional development enhancements added
  development:
    hot_reload: true
    mock_external_apis: true
    debug_mode: true
    cors_enabled: true

  # Optional notification integrations
  notifications:
    slack_webhook: "https://hooks.slack.com/services/XXX"
    discord_webhook: "https://discord.com/api/webhooks/YYY"
    email_alerts: false
